-- MySQL Script generated by MySQL Workbench
-- mié 17 jul 2019 21:38:13 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cventa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cventa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cventa` DEFAULT CHARACTER SET utf8 ;
USE `cventa` ;

-- -----------------------------------------------------
-- Table `cventa`.`cliente_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`cliente_tipo` (
  `cliente_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`cliente_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`pais_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`pais_empresa` (
  `pais_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `codigo_postal` VARCHAR(50) NULL,
  `iva` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`pais_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`moneda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`moneda` (
  `moneda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`moneda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`empresa` (
  `empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `direccion` VARCHAR(80) NOT NULL,
  `telefono` VARCHAR(80) NOT NULL,
  `representante` VARCHAR(50) NULL COMMENT 'Encargado de la empresa',
  `nit` VARCHAR(45) NULL,
  `abreviatura` VARCHAR(45) NOT NULL,
  `aplica_iva` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Monto de iva que aplica la empresa',
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `logo` TEXT NULL,
  `pais_empresa` INT NOT NULL,
  `moneda` INT NOT NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`empresa`),
  INDEX `fk_empresa_pais_empresa1_idx` (`pais_empresa` ASC),
  INDEX `fk_empresa_moneda1_idx` (`moneda` ASC),
  CONSTRAINT `fk_empresa_pais_empresa1`
    FOREIGN KEY (`pais_empresa`)
    REFERENCES `cventa`.`pais_empresa` (`pais_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_moneda1`
    FOREIGN KEY (`moneda`)
    REFERENCES `cventa`.`moneda` (`moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`rol` (
  `rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`usuario_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`usuario_genero` (
  `usuario_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `codigo` VARCHAR(25) NULL,
  PRIMARY KEY (`usuario_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`usuario` (
  `usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `alias` VARCHAR(40) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `identificacion` VARCHAR(50) NOT NULL COMMENT 'Número de DPI',
  `telefono` INT(12) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `foto` TEXT NULL,
  `firma` TEXT NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `jefe` TINYINT(1) NOT NULL DEFAULT 0,
  `subjefe` TINYINT(1) NOT NULL DEFAULT 0,
  `empresa` INT NOT NULL,
  `rol` INT NOT NULL,
  `root` TINYINT(1) NOT NULL DEFAULT 0,
  `usuario_genero` INT NOT NULL,
  `fecha_modificacion` TIMESTAMP NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_usuario_empresa1_idx` (`empresa` ASC),
  INDEX `fk_usuario_rol1_idx` (`rol` ASC),
  INDEX `fk_usuario_usuario_genero1_idx` (`usuario_genero` ASC),
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `cventa`.`rol` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_genero1`
    FOREIGN KEY (`usuario_genero`)
    REFERENCES `cventa`.`usuario_genero` (`usuario_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`cliente` (
  `cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nit` VARCHAR(45) NULL,
  `direccion` VARCHAR(70) NULL,
  `telefono` INT(12) NULL,
  `correo` VARCHAR(40) NULL,
  `cliente_tipo` INT NOT NULL,
  `aplica_descuento` TINYINT(1) NOT NULL DEFAULT 0,
  `monto_descuento` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `aplica_iva` TINYINT(1) NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `empresa` INT NOT NULL,
  `usuario` INT NOT NULL,
  INDEX `fk_cliente_cliente_tipo_idx` (`cliente_tipo` ASC),
  PRIMARY KEY (`cliente`),
  INDEX `fk_cliente_empresa1_idx` (`empresa` ASC),
  INDEX `fk_cliente_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_cliente_cliente_tipo`
    FOREIGN KEY (`cliente_tipo`)
    REFERENCES `cventa`.`cliente_tipo` (`cliente_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`usuario_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`usuario_empresa` (
  `usuario_empresa` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario` INT NOT NULL,
  `empresa` INT NOT NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_empresa`),
  INDEX `fk_usuario_empresa_usuario1_idx` (`usuario` ASC),
  INDEX `fk_usuario_empresa_empresa1_idx` (`empresa` ASC),
  CONSTRAINT `fk_usuario_empresa_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_empresa_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`modulo` (
  `modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `icono` VARCHAR(100) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `orden` INT NOT NULL DEFAULT 0,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`submenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`submenu` (
  `submenu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  PRIMARY KEY (`submenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`menu` (
  `menu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `icono` VARCHAR(100) NOT NULL,
  `orden` INT NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `modulo` INT NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `submenu` INT NOT NULL,
  PRIMARY KEY (`menu`),
  INDEX `fk_menu_modulo1_idx` (`modulo` ASC),
  INDEX `fk_menu_submenu1_idx` (`submenu` ASC),
  CONSTRAINT `fk_menu_modulo1`
    FOREIGN KEY (`modulo`)
    REFERENCES `cventa`.`modulo` (`modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_submenu1`
    FOREIGN KEY (`submenu`)
    REFERENCES `cventa`.`submenu` (`submenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`proveedor_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`proveedor_tipo` (
  `proveedor_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`proveedor_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`proveedor_clasificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`proveedor_clasificacion` (
  `proveedor_clasificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`proveedor_clasificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`proveedor` (
  `proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `telefono` INT(12) NOT NULL,
  `contacto` VARCHAR(100) NULL,
  `credito_contado` TINYINT(1) NOT NULL DEFAULT 0,
  `dias_credito` INT(11) NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `proveedor_tipo` INT NOT NULL,
  `proveedor_clasificacion` INT NOT NULL,
  `usuario` INT NOT NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`proveedor`),
  INDEX `fk_proveedor_proveedor_tipo1_idx` (`proveedor_tipo` ASC),
  INDEX `fk_proveedor_proveedor_clasificacion1_idx` (`proveedor_clasificacion` ASC),
  INDEX `fk_proveedor_usuario1_idx` (`usuario` ASC),
  INDEX `fk_proveedor_empresa1_idx` (`empresa` ASC),
  CONSTRAINT `fk_proveedor_proveedor_tipo1`
    FOREIGN KEY (`proveedor_tipo`)
    REFERENCES `cventa`.`proveedor_tipo` (`proveedor_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_proveedor_clasificacion1`
    FOREIGN KEY (`proveedor_clasificacion`)
    REFERENCES `cventa`.`proveedor_clasificacion` (`proveedor_clasificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proveedor_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bodega_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bodega_tipo` (
  `bodega_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`bodega_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bodega` (
  `bodega` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(100) NULL,
  `ubicacion` VARCHAR(100) NULL,
  `bodega_tipo` INT NOT NULL,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`bodega`),
  INDEX `fk_bodega_bodega_tipo1_idx` (`bodega_tipo` ASC),
  INDEX `fk_bodega_empresa1_idx` (`empresa` ASC),
  CONSTRAINT `fk_bodega_bodega_tipo1`
    FOREIGN KEY (`bodega_tipo`)
    REFERENCES `cventa`.`bodega_tipo` (`bodega_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bodega_movimiento_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bodega_movimiento_tipo` (
  `bodega_movimiento_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`bodega_movimiento_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`unidad_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`unidad_medida` (
  `unidad_medida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unidad_medida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`producto_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`producto_tipo` (
  `producto_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`producto_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`producto` (
  `producto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(300) NOT NULL,
  `nombre` VARCHAR(500) NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `unidad_medida` INT NOT NULL,
  `producto_tipo` INT NOT NULL,
  `precio_compra` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `precio_venta` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `incluye_iva` TINYINT(1) NOT NULL DEFAULT 0,
  `valor_iva` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_vencimiento` DATE NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `proveedor` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`producto`),
  INDEX `fk_producto_unidad_medida1_idx` (`unidad_medida` ASC),
  INDEX `fk_producto_producto_tipo1_idx` (`producto_tipo` ASC),
  INDEX `fk_producto_proveedor1_idx` (`proveedor` ASC),
  INDEX `fk_producto_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_producto_unidad_medida1`
    FOREIGN KEY (`unidad_medida`)
    REFERENCES `cventa`.`unidad_medida` (`unidad_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_producto_tipo1`
    FOREIGN KEY (`producto_tipo`)
    REFERENCES `cventa`.`producto_tipo` (`producto_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `cventa`.`proveedor` (`proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bodega_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bodega_movimiento` (
  `bodega_movimiento` INT NOT NULL AUTO_INCREMENT,
  `bodega` INT NOT NULL,
  `bodega_movimiento_tipo` INT NOT NULL,
  `fecha_accion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cantidad` INT(11) NOT NULL DEFAULT 0,
  `producto` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`bodega_movimiento`),
  INDEX `fk_bodega_movimiento_bodega1_idx` (`bodega` ASC),
  INDEX `fk_bodega_movimiento_bodega_movimiento_tipo1_idx` (`bodega_movimiento_tipo` ASC),
  INDEX `fk_bodega_movimiento_producto1_idx` (`producto` ASC),
  INDEX `fk_bodega_movimiento_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_bodega_movimiento_bodega1`
    FOREIGN KEY (`bodega`)
    REFERENCES `cventa`.`bodega` (`bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_movimiento_bodega_movimiento_tipo1`
    FOREIGN KEY (`bodega_movimiento_tipo`)
    REFERENCES `cventa`.`bodega_movimiento_tipo` (`bodega_movimiento_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_movimiento_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `cventa`.`producto` (`producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_movimiento_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bodega_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bodega_producto` (
  `bodega_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` INT NOT NULL,
  `bodega` INT NOT NULL,
  `fecha_ingreso` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`bodega_producto`),
  INDEX `fk_bodega_producto_producto1_idx` (`producto` ASC),
  INDEX `fk_bodega_producto_bodega1_idx` (`bodega` ASC),
  INDEX `fk_bodega_producto_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_bodega_producto_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `cventa`.`producto` (`producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_producto_bodega1`
    FOREIGN KEY (`bodega`)
    REFERENCES `cventa`.`bodega` (`bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bodega_producto_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`venta_estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`venta_estatus` (
  `venta_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`venta_estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`compra_estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`compra_estatus` (
  `compra_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`compra_estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`factura_estatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`factura_estatus` (
  `factura_estatus` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`factura_estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`tipo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`tipo_pago` (
  `tipo_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`venta` (
  `venta` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `concepto` VARCHAR(500) NOT NULL,
  `valor_base` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `iva` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `monto` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `saldo` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `venta_estatus` INT NOT NULL,
  `tipo_pago` INT NOT NULL,
  `usuario` INT NOT NULL,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `moneda` INT NOT NULL,
  PRIMARY KEY (`venta`),
  INDEX `fk_venta_cliente1_idx` (`cliente` ASC),
  INDEX `fk_venta_venta_estatus1_idx` (`venta_estatus` ASC),
  INDEX `fk_venta_tipo_pago1_idx` (`tipo_pago` ASC),
  INDEX `fk_venta_usuario1_idx` (`usuario` ASC),
  INDEX `fk_venta_moneda1_idx` (`moneda` ASC),
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `cventa`.`cliente` (`cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_venta_estatus1`
    FOREIGN KEY (`venta_estatus`)
    REFERENCES `cventa`.`venta_estatus` (`venta_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_tipo_pago1`
    FOREIGN KEY (`tipo_pago`)
    REFERENCES `cventa`.`tipo_pago` (`tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_moneda1`
    FOREIGN KEY (`moneda`)
    REFERENCES `cventa`.`moneda` (`moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`factura_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`factura_serie` (
  `factura_serie` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NULL,
  `codigo` VARCHAR(45) NULL,
  `inicio` INT(11) NOT NULL DEFAULT 1,
  `fin` INT(11) NOT NULL DEFAULT 0,
  `correlativo` INT(11) NOT NULL DEFAULT 0,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`factura_serie`),
  INDEX `fk_venta_serie_empresa1_idx` (`empresa` ASC),
  CONSTRAINT `fk_venta_serie_empresa1`
    FOREIGN KEY (`empresa`)
    REFERENCES `cventa`.`empresa` (`empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`venta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`venta_detalle` (
  `venta_detalle` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL DEFAULT 0,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `anulado` TINYINT(1) NOT NULL DEFAULT 0,
  `venta` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`venta_detalle`),
  INDEX `fk_venta_detalle_venta1_idx` (`venta` ASC),
  INDEX `fk_venta_detalle_producto1_idx` (`producto` ASC),
  CONSTRAINT `fk_venta_detalle_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `cventa`.`venta` (`venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_detalle_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `cventa`.`producto` (`producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`compra` (
  `compra` INT NOT NULL AUTO_INCREMENT,
  `valor_base` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `valor_iva` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `monto` DECIMAL(10,2) NULL,
  `fecha_factura` DATE NOT NULL,
  `factura_numero` VARCHAR(80) NOT NULL,
  `serie` VARCHAR(50) NOT NULL,
  `concepto` VARCHAR(500) NULL,
  `fecha_pago` DATE NOT NULL,
  `fecha_compra` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `proveedor` INT NOT NULL,
  `compra_estatus` INT NOT NULL,
  `tipo_pago` INT NOT NULL,
  `usuario` INT NOT NULL,
  `moneda` INT NOT NULL,
  PRIMARY KEY (`compra`),
  INDEX `fk_compra_proveedor1_idx` (`proveedor` ASC),
  INDEX `fk_compra_compra_estatus1_idx` (`compra_estatus` ASC),
  INDEX `fk_compra_tipo_pago1_idx` (`tipo_pago` ASC),
  INDEX `fk_compra_usuario1_idx` (`usuario` ASC),
  INDEX `fk_compra_moneda1_idx` (`moneda` ASC),
  CONSTRAINT `fk_compra_proveedor1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `cventa`.`proveedor` (`proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_compra_estatus1`
    FOREIGN KEY (`compra_estatus`)
    REFERENCES `cventa`.`compra_estatus` (`compra_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_tipo_pago1`
    FOREIGN KEY (`tipo_pago`)
    REFERENCES `cventa`.`tipo_pago` (`tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_moneda1`
    FOREIGN KEY (`moneda`)
    REFERENCES `cventa`.`moneda` (`moneda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`factura` (
  `factura` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `numero` VARCHAR(45) NULL,
  `monto` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `factura_estatus` INT NOT NULL,
  `usuario` INT NOT NULL,
  `factura_serie` INT NOT NULL,
  PRIMARY KEY (`factura`),
  INDEX `fk_factura_factura_estatus1_idx` (`factura_estatus` ASC),
  INDEX `fk_factura_usuario1_idx` (`usuario` ASC),
  INDEX `fk_factura_factura_serie1_idx` (`factura_serie` ASC),
  CONSTRAINT `fk_factura_factura_estatus1`
    FOREIGN KEY (`factura_estatus`)
    REFERENCES `cventa`.`factura_estatus` (`factura_estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_factura_serie1`
    FOREIGN KEY (`factura_serie`)
    REFERENCES `cventa`.`factura_serie` (`factura_serie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`factura_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`factura_venta` (
  `factura_venta` INT NOT NULL AUTO_INCREMENT,
  `factura` INT NOT NULL,
  `venta` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `anulado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`factura_venta`),
  INDEX `fk_factura_venta_factura1_idx` (`factura` ASC),
  INDEX `fk_factura_venta_venta1_idx` (`venta` ASC),
  CONSTRAINT `fk_factura_venta_factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `cventa`.`factura` (`factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_venta_venta1`
    FOREIGN KEY (`venta`)
    REFERENCES `cventa`.`venta` (`venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`vendedor` (
  `vendedor` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`vendedor`),
  INDEX `fk_vendedor_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`vendedor_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`vendedor_cliente` (
  `vendedor_cliente` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `vendedor` INT NOT NULL,
  `cliente` INT NOT NULL,
  PRIMARY KEY (`vendedor_cliente`),
  INDEX `fk_vendedor_cliente_vendedor1_idx` (`vendedor` ASC),
  INDEX `fk_vendedor_cliente_cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_vendedor_cliente_vendedor1`
    FOREIGN KEY (`vendedor`)
    REFERENCES `cventa`.`vendedor` (`vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_cliente_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `cventa`.`cliente` (`cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`usuario_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`usuario_menu` (
  `usuario_menu` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_sis` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `usuario` INT NOT NULL,
  `menu` INT NOT NULL,
  PRIMARY KEY (`usuario_menu`),
  INDEX `fk_usuario_menu_usuario1_idx` (`usuario` ASC),
  INDEX `fk_usuario_menu_menu1_idx` (`menu` ASC),
  CONSTRAINT `fk_usuario_menu_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_menu_menu1`
    FOREIGN KEY (`menu`)
    REFERENCES `cventa`.`menu` (`menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`bitacora_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`bitacora_password` (
  `bitacora_password` INT NOT NULL AUTO_INCREMENT,
  `fecha_cambio` DATETIME NOT NULL,
  `ip` VARCHAR(45) NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`bitacora_password`),
  INDEX `fk_bitacora_password_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_bitacora_password_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `cventa`.`usuario` (`usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cventa`.`compra_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cventa`.`compra_detalle` (
  `compra_detalle` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `cantidad` INT NOT NULL DEFAULT 0,
  `total` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `anulado` TINYINT(1) NOT NULL DEFAULT 0,
  `compra` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`compra_detalle`),
  INDEX `fk_compra_detalle_compra1_idx` (`compra` ASC),
  INDEX `fk_compra_detalle_producto1_idx` (`producto` ASC),
  CONSTRAINT `compra`
    FOREIGN KEY (`compra`)
    REFERENCES `cventa`.`compra` (`compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto`
    FOREIGN KEY (`producto`)
    REFERENCES `cventa`.`producto` (`producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
